// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc3y0pLwSXsh2NKzq6q6LN2MK_aEpEz7c',
    appId: '1:230595536472:web:72a78f8fc368fedd884c2d',
    messagingSenderId: '230595536472',
    projectId: 'recipe-app-3384d',
    authDomain: 'recipe-app-3384d.firebaseapp.com',
    storageBucket: 'recipe-app-3384d.appspot.com',
    measurementId: 'G-TD8PSJ4XQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3XUjg2dxVr-sNSpnEWzT9zmXBVK1W2vU',
    appId: '1:230595536472:android:4110247051c30d14884c2d',
    messagingSenderId: '230595536472',
    projectId: 'recipe-app-3384d',
    storageBucket: 'recipe-app-3384d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoHspOmCsimLI1ybM-UznVD0WafwQumt4',
    appId: '1:230595536472:ios:f528ae4de2ab4bf2884c2d',
    messagingSenderId: '230595536472',
    projectId: 'recipe-app-3384d',
    storageBucket: 'recipe-app-3384d.appspot.com',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoHspOmCsimLI1ybM-UznVD0WafwQumt4',
    appId: '1:230595536472:ios:f528ae4de2ab4bf2884c2d',
    messagingSenderId: '230595536472',
    projectId: 'recipe-app-3384d',
    storageBucket: 'recipe-app-3384d.appspot.com',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBc3y0pLwSXsh2NKzq6q6LN2MK_aEpEz7c',
    appId: '1:230595536472:web:6e6f21230547d097884c2d',
    messagingSenderId: '230595536472',
    projectId: 'recipe-app-3384d',
    authDomain: 'recipe-app-3384d.firebaseapp.com',
    storageBucket: 'recipe-app-3384d.appspot.com',
    measurementId: 'G-MB4RKDYKSL',
  );
}
